singularity: "/gpfs/home/shkhalid/SiepelVeeramahSharedDrive/argsortium-inference/shared/container/arg_inference_tools.sif"
params_csv: "/gpfs/projects/SiepelVeeramahGroup/shkhalid/argsortium-inference/singer/myconfigs/2026_05_11_runs/master_params.csv"

Ne: 20000
mcmc_samples: 2000
step_size: 20
thin: 20
polar: 0.99
