# config.yaml

singularity: "/grid/siepel/home/khalid/argsortium-inference/shared/container/arg_inference_tools.sif"
params_csv: "/grid/siepel/home/khalid/argsortium-inference/argweaver/myconfigs/2026_05_11_runs/master_params.csv"

# Model parameters
Ne: 10000
recomb_rate: 1.2e-8
mcmc_samples: 4000
compression: 20
n_time_points: 20
sample_step: 20
