configfile: f"{workflow.basedir}/config.yaml"

import csv
import os

params = {}
uids = []

with open(config["params_csv"]) as f:
    for row in csv.DictReader(f):
        uid = row["uid"]
        params[uid] = row
        uids.append(uid)

SAMPLE_STEP = config.get("sample_step", 10)
FINAL_ITER  = config.get("mcmc_samples", 4000)
PENULTIMATE = FINAL_ITER - SAMPLE_STEP

all_targets = [
    f"{params[uid]['output_dir']}/{uid}/{uid}.{PENULTIMATE}.smc.gz"
    for uid in uids
]

wildcard_constraints:
    uid   = r"[^/]+",   # uid never crosses a directory boundary
    outdir = r".+"      # outdir can contain slashes (full path)


rule all:
    input: all_targets


rule vcf_to_sites:
    input:
        vcf = lambda wc: params[wc.uid]["vcf_file"]
    output:
        sites = "{outdir}/{uid}.sites"
    container: config.get("singularity")
    shell:
        """
        python {workflow.basedir}/scripts/vcf2sites.py --vcf {input.vcf} --out {output.sites}
        """


rule hapmap_to_bedgraph:
    input:
        hapmap = lambda wc: params[wc.uid]["recomb_map"]
    output:
        bedgraph = "{outdir}/{uid}.bedgraph"
    shell:
        """
        python {workflow.basedir}/scripts/hapmap_to_bedgraph.py --hapmap {input.hapmap} --out {output.bedgraph}
        """


rule run_argweaver:
    input:
        sites    = "{outdir}/{uid}.sites",
        bedgraph = "{outdir}/{uid}.bedgraph"
    output:
        smc = f"{{outdir}}/{{uid}}/{{uid}}.{PENULTIMATE}.smc.gz"
    params:
        Ne          = config.get("Ne", 10000),
        mu          = lambda wc: params[wc.uid]["mu"],
        ntimes      = config.get("n_time_points", 20),
        compression = config.get("compression", 20),
        n_iters     = FINAL_ITER,
        sample_step = SAMPLE_STEP,
        start       = lambda wc: params[wc.uid]["inference_start"],
        end         = lambda wc: params[wc.uid]["inference_end"],
        out_prefix  = "{outdir}/{uid}/{uid}"
    container: config.get("singularity")
    shell:
        """
        mkdir -p $(dirname {output.smc})

        RESUME_FLAG=""
        if [ -f "{params.out_prefix}.stats" ] && \
           compgen -G "{params.out_prefix}.*.smc.gz" > /dev/null; then
            RESUME_FLAG="--resume"
        fi

        arg-sample $RESUME_FLAG \
          -s {input.sites} \
          -N {params.Ne} \
          -R {input.bedgraph} \
          -m {params.mu} \
          -t {params.ntimes} \
          -c {params.compression} \
          -n {params.n_iters} \
          --sample-step {params.sample_step} \
          --region {params.start}-{params.end} \
          -o {params.out_prefix}
        """
